<?php

declare(strict_types=1);

namespace Rowbot\DOM\Tests\dom\nodes;

use Rowbot\DOM\Exception\InvalidCharacterError;
use Rowbot\DOM\Exception\NamespaceError;

/**
 * @see https://github.com/w3c/web-platform-tests/blob/master/dom/nodes/Document-createElementNS.js
 */
trait CreateElementNSTests
{
    public function getCreateElementNSTests(): array
    {
        return [
            /* Arrays with three elements:
             *   the namespace argument
             *   the qualifiedName argument
             *   the expected exception, or null if none
             */
            // [null, null, null],
            // [null, undefined, null],
            [null, "foo", null],
            [null, "1foo", InvalidCharacterError::class],
            [null, "f1oo", null],
            [null, "foo1", null],
            [null, "\u{0BC6}foo", null],
            [null, "\u{037E}foo", InvalidCharacterError::class],
            [null, "}foo", InvalidCharacterError::class],
            [null, "f}oo", InvalidCharacterError::class],
            [null, "foo}", InvalidCharacterError::class],
            [null, "\u{FFFF}foo", InvalidCharacterError::class],
            [null, "f\u{FFFF}oo", InvalidCharacterError::class],
            [null, "foo\u{FFFF}", InvalidCharacterError::class],
            [null, "<foo", InvalidCharacterError::class],
            [null, "foo>", InvalidCharacterError::class],
            [null, "<foo>", InvalidCharacterError::class],
            [null, "f<oo", InvalidCharacterError::class],
            [null, "^^", InvalidCharacterError::class],
            [null, "fo o", InvalidCharacterError::class],
            [null, "-foo", InvalidCharacterError::class],
            [null, ".foo", InvalidCharacterError::class],
            [null, ":foo", InvalidCharacterError::class],
            [null, "f:oo", NamespaceError::class],
            [null, "foo:", InvalidCharacterError::class],
            [null, "f:o:o", InvalidCharacterError::class],
            [null, ":", InvalidCharacterError::class],
            [null, "xml", null],
            [null, "xmlns", NamespaceError::class],
            [null, "xmlfoo", null],
            [null, "xml:foo", NamespaceError::class],
            [null, "xmlns:foo", NamespaceError::class],
            [null, "xmlfoo:bar", NamespaceError::class],
            [null, "null:xml", NamespaceError::class],
            // ["", null, null],
            ["", ":foo", InvalidCharacterError::class],
            ["", "f:oo", NamespaceError::class],
            ["", "foo:", InvalidCharacterError::class],
            // [undefined, null, null],
            // [undefined, undefined, null],
            // [undefined, "foo", null],
            // [undefined, "1foo", InvalidCharacterError::class],
            // [undefined, "f1oo", null],
            // [undefined, "foo1", null],
            // [undefined, ":foo", InvalidCharacterError::class],
            // [undefined, "f:oo", NamespaceError::class],
            // [undefined, "foo:", InvalidCharacterError::class],
            // [undefined, "f::oo", InvalidCharacterError::class],
            // [undefined, "xml", null],
            // [undefined, "xmlns", NamespaceError::class],
            // [undefined, "xmlfoo", null],
            // [undefined, "xml:foo", NamespaceError::class],
            // [undefined, "xmlns:foo", NamespaceError::class],
            // [undefined, "xmlfoo:bar", NamespaceError::class],
            ["http://example.com/", "foo", null],
            ["http://example.com/", "1foo", InvalidCharacterError::class],
            ["http://example.com/", "<foo>", InvalidCharacterError::class],
            ["http://example.com/", "fo<o", InvalidCharacterError::class],
            ["http://example.com/", "-foo", InvalidCharacterError::class],
            ["http://example.com/", ".foo", InvalidCharacterError::class],
            ["http://example.com/", "f1oo", null],
            ["http://example.com/", "foo1", null],
            ["http://example.com/", ":foo", InvalidCharacterError::class],
            ["http://example.com/", "f:oo", null],
            ["http://example.com/", "f:o:o", InvalidCharacterError::class],
            ["http://example.com/", "foo:", InvalidCharacterError::class],
            ["http://example.com/", "f::oo", InvalidCharacterError::class],
            ["http://example.com/", "a:0", InvalidCharacterError::class],
            ["http://example.com/", "0:a", InvalidCharacterError::class],
            ["http://example.com/", "a:_", null],
            ["http://example.com/", "a:\u{0BC6}", null],
            ["http://example.com/", "a:\u{037E}", InvalidCharacterError::class],
            ["http://example.com/", "a:\u{0300}", InvalidCharacterError::class],
            ["http://example.com/", "\u{0BC6}:a", null],
            ["http://example.com/", "\u{0300}:a", InvalidCharacterError::class],
            ["http://example.com/", "\u{037E}:a", InvalidCharacterError::class],
            ["http://example.com/", "a:a\u{0BC6}", null],
            ["http://example.com/", "a\u{0BC6}:a", null],
            ["http://example.com/", "xml:test", NamespaceError::class],
            ["http://example.com/", "xmlns:test", NamespaceError::class],
            ["http://example.com/", "test:xmlns", null],
            ["http://example.com/", "xmlns", NamespaceError::class],
            ["http://example.com/", "_:_", null],
            ["http://example.com/", "_:h0", null],
            ["http://example.com/", "_:test", null],
            ["http://example.com/", "l_:_", null],
            ["http://example.com/", "ns:_0", null],
            ["http://example.com/", "ns:a0", null],
            ["http://example.com/", "ns0:test", null],
            ["http://example.com/", "a.b:c", null],
            ["http://example.com/", "a-b:c", null],
            ["http://example.com/", "xml", null],
            ["http://example.com/", "XMLNS", null],
            ["http://example.com/", "xmlfoo", null],
            ["http://example.com/", "xml:foo", NamespaceError::class],
            ["http://example.com/", "XML:foo", null],
            ["http://example.com/", "xmlns:foo", NamespaceError::class],
            ["http://example.com/", "XMLNS:foo", null],
            ["http://example.com/", "xmlfoo:bar", null],
            ["http://example.com/", "prefix::local", InvalidCharacterError::class],
            ["http://example.com/", "namespaceURI:{", InvalidCharacterError::class],
            ["http://example.com/", "namespaceURI:}", InvalidCharacterError::class],
            ["http://example.com/", "namespaceURI:~", InvalidCharacterError::class],
            ["http://example.com/", "namespaceURI:'", InvalidCharacterError::class],
            ["http://example.com/", "namespaceURI:!", InvalidCharacterError::class],
            ["http://example.com/", "namespaceURI:@", InvalidCharacterError::class],
            ["http://example.com/", "namespaceURI:#", InvalidCharacterError::class],
            ["http://example.com/", "namespaceURI:$", InvalidCharacterError::class],
            ["http://example.com/", "namespaceURI:%", InvalidCharacterError::class],
            ["http://example.com/", "namespaceURI:^", InvalidCharacterError::class],
            ["http://example.com/", "namespaceURI:&", InvalidCharacterError::class],
            ["http://example.com/", "namespaceURI:*", InvalidCharacterError::class],
            ["http://example.com/", "namespaceURI:(", InvalidCharacterError::class],
            ["http://example.com/", "namespaceURI:)", InvalidCharacterError::class],
            ["http://example.com/", "namespaceURI:+", InvalidCharacterError::class],
            ["http://example.com/", "namespaceURI:=", InvalidCharacterError::class],
            ["http://example.com/", "namespaceURI:[", InvalidCharacterError::class],
            ["http://example.com/", "namespaceURI:]", InvalidCharacterError::class],
            ["http://example.com/", "namespaceURI:\\", InvalidCharacterError::class],
            ["http://example.com/", "namespaceURI:/", InvalidCharacterError::class],
            ["http://example.com/", "namespaceURI:;", InvalidCharacterError::class],
            ["http://example.com/", "namespaceURI:`", InvalidCharacterError::class],
            ["http://example.com/", "namespaceURI:<", InvalidCharacterError::class],
            ["http://example.com/", "namespaceURI:>", InvalidCharacterError::class],
            ["http://example.com/", "namespaceURI:,", InvalidCharacterError::class],
            ["http://example.com/", "namespaceURI:a ", InvalidCharacterError::class],
            ["http://example.com/", "namespaceURI:\"", InvalidCharacterError::class],
            ["/", "foo", null],
            ["/", "1foo", InvalidCharacterError::class],
            ["/", "f1oo", null],
            ["/", "foo1", null],
            ["/", ":foo", InvalidCharacterError::class],
            ["/", "f:oo", null],
            ["/", "foo:", InvalidCharacterError::class],
            ["/", "xml", null],
            ["/", "xmlns", NamespaceError::class],
            ["/", "xmlfoo", null],
            ["/", "xml:foo", NamespaceError::class],
            ["/", "xmlns:foo", NamespaceError::class],
            ["/", "xmlfoo:bar", null],
            ["http://www.w3.org/XML/1998/namespace", "foo", null],
            ["http://www.w3.org/XML/1998/namespace", "1foo", InvalidCharacterError::class],
            ["http://www.w3.org/XML/1998/namespace", "f1oo", null],
            ["http://www.w3.org/XML/1998/namespace", "foo1", null],
            ["http://www.w3.org/XML/1998/namespace", ":foo", InvalidCharacterError::class],
            ["http://www.w3.org/XML/1998/namespace", "f:oo", null],
            ["http://www.w3.org/XML/1998/namespace", "foo:", InvalidCharacterError::class],
            ["http://www.w3.org/XML/1998/namespace", "xml", null],
            ["http://www.w3.org/XML/1998/namespace", "xmlns", NamespaceError::class],
            ["http://www.w3.org/XML/1998/namespace", "xmlfoo", null],
            ["http://www.w3.org/XML/1998/namespace", "xml:foo", null],
            ["http://www.w3.org/XML/1998/namespace", "xmlns:foo", NamespaceError::class],
            ["http://www.w3.org/XML/1998/namespace", "xmlfoo:bar", null],
            ["http://www.w3.org/XML/1998/namespaces", "xml:foo", NamespaceError::class],
            ["http://www.w3.org/xml/1998/namespace", "xml:foo", NamespaceError::class],
            ["http://www.w3.org/2000/xmlns/", "foo", NamespaceError::class],
            ["http://www.w3.org/2000/xmlns/", "1foo", InvalidCharacterError::class],
            ["http://www.w3.org/2000/xmlns/", "f1oo", NamespaceError::class],
            ["http://www.w3.org/2000/xmlns/", "foo1", NamespaceError::class],
            ["http://www.w3.org/2000/xmlns/", ":foo", InvalidCharacterError::class],
            ["http://www.w3.org/2000/xmlns/", "f:oo", NamespaceError::class],
            ["http://www.w3.org/2000/xmlns/", "foo:", InvalidCharacterError::class],
            ["http://www.w3.org/2000/xmlns/", "xml", NamespaceError::class],
            ["http://www.w3.org/2000/xmlns/", "xmlns", null],
            ["http://www.w3.org/2000/xmlns/", "xmlfoo", NamespaceError::class],
            ["http://www.w3.org/2000/xmlns/", "xml:foo", NamespaceError::class],
            ["http://www.w3.org/2000/xmlns/", "xmlns:foo", null],
            ["http://www.w3.org/2000/xmlns/", "xmlfoo:bar", NamespaceError::class],
            ["http://www.w3.org/2000/xmlns/", "foo:xmlns", NamespaceError::class],
            ["foo:", "foo", null],
            ["foo:", "1foo", InvalidCharacterError::class],
            ["foo:", "f1oo", null],
            ["foo:", "foo1", null],
            ["foo:", ":foo", InvalidCharacterError::class],
            ["foo:", "f:oo", null],
            ["foo:", "foo:", InvalidCharacterError::class],
            ["foo:", "xml", null],
            ["foo:", "xmlns", NamespaceError::class],
            ["foo:", "xmlfoo", null],
            ["foo:", "xml:foo", NamespaceError::class],
            ["foo:", "xmlns:foo", NamespaceError::class],
            ["foo:", "xmlfoo:bar", null],
        ];
    }
}
