name: Test
on: [push, pull_request]
jobs:
  test:
    name: Test PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }} ${{ matrix.arch }}
    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['7.1', '7.2', '7.3', '7.4', '8.0']
        arch: ['amd64']
        phpunit-flags: ['--prefer-dist --optimize-autoloader']
        include:
          - php-versions: '7.1'
            operating-system: 'ubuntu-latest'
            arch: 'i386'

          - php-versions: '8.1'
            operating-system: 'ubuntu-latest'
            arch: 'amd64'
            phpunit-flags: '--prefer-dist --optimize-autoloader --ignore-platform-reqs'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ctype, json, mbstring, opcache, pcre, gmp
          ini-values: zend.assertions=1
          coverage: pcov

      - name: Setup PCOV
        if: ${{ matrix.php-versions == '7.1' }}
        run: |
          composer require pcov/clobber
          vendor/bin/pcov clobber

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install ${{ matrix.phpunit-flags }}

      - name: Run Tests
        run: vendor/bin/phpunit --coverage-clover ./build/coverage/clover.xml
        continue-on-error: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/coverage/clover.xml
