name: Test PHPDOM
on:
  push:
    paths-ignore:
      - '**.md'

  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: Test PHP ${{ matrix.php-versions }} on ubuntu
    runs-on: 'ubuntu-latest'

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.1', '7.2', '7.4', '8.0']
        composer-options: ['--optimize-autoloader']
        coverage: ['none']
        include:
          - php-versions: '7.3'
            composer-options: '--optimize-autoloader'
            coverage: 'pcov'

          - php-versions: '8.1'
            composer-options: '--optimize-autoloader --ignore-platform-reqs'
            coverage: 'none'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ctype, json, mbstring, opcache, pcre, gmp
          ini-values: zend.assertions=1
          coverage: ${{ matrix.coverage }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer update ${{ matrix.composer-options }}

      - name: Run Tests
        run: |
          if [[ ${{ matrix.php-versions == '7.3' }} ]]; then
            mkdir -p ./build/coverage/
            vendor/bin/phpunit --coverage-clover ./build/coverage/clover.xml
          else
            vendor/bin/phpunit --no-coverage
          fi

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: ${{ always() && matrix.php-versions == '7.3' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/coverage/clover.xml
          name: PHP ${{ matrix.php-versions }}
